# Generated by Django 3.2.5 on 2021-08-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=150)),
                ('product_color', models.CharField(max_length=50)),
                ('product_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('product_material', models.CharField(max_length=200)),
                ('product_material_advantage', models.TextField()),
            ],
        ),
    ]
